//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingAvailabilityWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Collaborators
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Matricule { get; set; }
        public string Gender { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Rank { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public bool PlaceHolder { get; set; }
        public int PlaceNumber { get; set; }
    }
}
