//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParkingAvailabilityWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParkingPlace
    {
        public int Id { get; set; }
        public int PlaceNumber { get; set; }
        public string PlaceDescription { get; set; }
        public int BadgeID { get; set; }
        public string Statut { get; set; }
    }
}
